name: release build

on:
  push:
    tags:
      - 'v*'

jobs:
  build_test:
    uses: ./.github/workflows/test-template.yml

  pack_push:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Pack NuGet
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          VERSION=${REF_NAME#v}
          dotnet pack -c Release \
            -p:PackageVersion=$VERSION \
            -o ./artifacts \
            -p:IncludeSymbols=true \
            -p:SymbolPackageFormat=snupkg

      - name: Push NuGet
        run: |
          dotnet nuget push "./artifacts/*.nupkg" -s https://api.nuget.org/v3/index.json -k "${{ secrets.NUGET_API_KEY }}" --skip-duplicate
          dotnet nuget push "./artifacts/*.snupkg" -s https://api.nuget.org/v3/index.json -k "${{ secrets.NUGET_API_KEY }}" --skip-duplicate
